# Configuration for development environment

# HugginfFace inference providers: https://huggingface.co/inference/models

# Planner Agent settings
PLANNER:
  MODEL_ID: "moonshotai/Kimi-K2-Thinking"
  PROVIDER: "auto"

# Splitter Agent settings; Tools: Yes, Structured: Yes
SPLITTER:
  MODEL_ID: "deepseek-ai/DeepSeek-V3.2-Exp"
  PROVIDER: "novita"

# Coordinator Agent settings; Tools: Yes, Structured: Yes
COORDINATOR:
  MODEL_ID: "openai/gpt-oss-120b"
  #MODEL_ID: "MiniMaxAI/MiniMax-M1-80k"
  PROVIDER: "novita"

# Subagent settings; Tools: Yes, Structured: Yes
SUBAGENT:
  MODEL_ID: "openai/gpt-oss-120b"
  #MODEL_ID: "MiniMaxAI/MiniMax-M1-80k"
  PROVIDER: "novita"